package book.store.view;

import book.store.entity.Book;
import book.store.entity.Response;
import book.store.entity.User;
import book.store.repository.BookRepository;
import book.store.repository.UserRepository;
import book.store.repository.impl.BookRepositoryImpl;
import book.store.repository.impl.UserRepositoryImpl;
import book.store.services.BookService;
import book.store.services.UserService;
import java.awt.CardLayout;
import java.awt.Color;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author hadir
 */
public class MenuFrame extends javax.swing.JFrame {

    private final Logger log = LoggerFactory.getLogger(MenuFrame.class);
    private final BookRepository bookRepository = new BookRepositoryImpl();
    private final BookService bookService = new BookService(bookRepository);
    private final UserRepository userRepository = new UserRepositoryImpl();
    private final UserService userService = new UserService(userRepository);
    private User user;

    CardLayout cardLayout;
    
    public MenuFrame(User user) {
        this.user = user;
        log.info("{} is login", user.getUsername());
        initComponents();
        cardLayout = (CardLayout)(panelData.getLayout()) ;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        panelMenu = new javax.swing.JPanel();
        btnUpdate = new java.awt.Button();
        btnSave = new java.awt.Button();
        btnFind = new java.awt.Button();
        btnDelete = new java.awt.Button();
        btnAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelData = new javax.swing.JPanel();
        panelSave = new javax.swing.JPanel();
        saveLabel = new java.awt.Label();
        quantityLabel = new java.awt.Label();
        quantityField = new javax.swing.JTextField();
        nameLabel = new java.awt.Label();
        nameField = new javax.swing.JTextField();
        authorLabel1 = new java.awt.Label();
        auhtorField = new javax.swing.JTextField();
        publihserLabel1 = new java.awt.Label();
        publihserField1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        labelInfo = new javax.swing.JLabel();
        panelDelete = new javax.swing.JPanel();
        deleteTitle = new javax.swing.JLabel();
        deleteNameInputLabel = new javax.swing.JLabel();
        deleteBookINameInput = new javax.swing.JTextField();
        deleteFindBtn = new javax.swing.JButton();
        deleteInfoSearch = new javax.swing.JLabel();
        deleteAuthorLabel = new javax.swing.JLabel();
        deleteNameLabel = new javax.swing.JLabel();
        deletePublisherLabel = new javax.swing.JLabel();
        deleteQuantityLabel = new javax.swing.JLabel();
        deleteNameBookLabel = new javax.swing.JLabel();
        deleteAuthorBookLabel = new javax.swing.JLabel();
        deletePubllisherBookLabel = new javax.swing.JLabel();
        deleteQuantityBookLabel = new javax.swing.JLabel();
        deleteBookBtn = new javax.swing.JButton();
        deleteInfoLabel = new javax.swing.JLabel();
        panelFind = new javax.swing.JPanel();
        findTitleLabel = new javax.swing.JLabel();
        findBookNameLabel = new javax.swing.JLabel();
        findBookNameField = new javax.swing.JTextField();
        findBookNameBtn = new javax.swing.JButton();
        findInfoLabel = new javax.swing.JLabel();
        findLabelBookName = new javax.swing.JLabel();
        findLabelBookAuhtor = new javax.swing.JLabel();
        findLabelBookPublisher = new javax.swing.JLabel();
        findLabelBookQuantity = new javax.swing.JLabel();
        findBookUpdateBtn = new javax.swing.JButton();
        findBookDeleteBtn = new javax.swing.JButton();
        findBookName = new javax.swing.JLabel();
        findBookAuthor = new javax.swing.JLabel();
        findBookPublisher = new javax.swing.JLabel();
        findBookQuantity = new javax.swing.JLabel();
        findInfoResultLabel = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        updateTitleLabel = new javax.swing.JLabel();
        updateBookInputLabel = new javax.swing.JLabel();
        updateBookInputField = new javax.swing.JTextField();
        updateSearchBtn = new javax.swing.JButton();
        updateInfoLabel = new javax.swing.JLabel();
        updateNameLabel = new javax.swing.JLabel();
        updateAuhtorLabel = new javax.swing.JLabel();
        updatePublihserLabel = new javax.swing.JLabel();
        updateQuantityLabel = new javax.swing.JLabel();
        updateAuhtorField = new javax.swing.JTextField();
        updatePublisherField = new javax.swing.JTextField();
        updateQuantityField = new javax.swing.JTextField();
        updateBookBtn = new javax.swing.JButton();
        updateInfoResultLabel = new javax.swing.JLabel();
        updateNameField = new javax.swing.JLabel();
        panelAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailAccountField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accountIdField = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameAccountField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernameAccountField = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        infoDeleteAcct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("menuFrame"); // NOI18N

        panelMenu.setBackground(new java.awt.Color(0, 0, 255));
        panelMenu.setName("panelMenu"); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(300, 600));

        btnUpdate.setActionCommand("btnUpdate");
        btnUpdate.setBackground(new java.awt.Color(0, 0, 255));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setLabel("UPDATE BOOK");
        btnUpdate.setPreferredSize(new java.awt.Dimension(200, 65));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 255));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setLabel("SAVE BOOK");
        btnSave.setPreferredSize(new java.awt.Dimension(200, 65));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnFind.setActionCommand("btnFind");
        btnFind.setBackground(new java.awt.Color(0, 0, 255));
        btnFind.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFind.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setLabel("FIND BOOK");
        btnFind.setPreferredSize(new java.awt.Dimension(200, 65));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnDelete.setActionCommand("btnDelete");
        btnDelete.setBackground(new java.awt.Color(0, 0, 255));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setLabel("DELETE BOOK");
        btnDelete.setPreferredSize(new java.awt.Dimension(200, 65));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAccount.setBackground(new java.awt.Color(0, 0, 255));
        btnAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount.setBorder(null);
        btnAccount.setLabel("ME");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        btnUpdate.getAccessibleContext().setAccessibleName("btnUpdate");
        btnFind.getAccessibleContext().setAccessibleName("btnFind");
        btnDelete.getAccessibleContext().setAccessibleName("btnDelete");

        jSplitPane2.setLeftComponent(panelMenu);

        panelData.setLayout(new java.awt.CardLayout());

        panelSave.setBackground(new java.awt.Color(255, 255, 255));

        saveLabel.setAlignment(java.awt.Label.CENTER);
        saveLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saveLabel.setText("Save Book");

        quantityLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        quantityLabel.setText("Quantity");

        quantityField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quantityField.setText("0");
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameLabel.setText("Book Name");

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        authorLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        authorLabel1.setText("Auhtor");

        auhtorField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        auhtorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auhtorFieldActionPerformed(evt);
            }
        });

        publihserLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        publihserLabel1.setText("Publisher");

        publihserField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        publihserField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publihserField1ActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        labelInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelSaveLayout = new javax.swing.GroupLayout(panelSave);
        panelSave.setLayout(panelSaveLayout);
        panelSaveLayout.setHorizontalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaveLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(saveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(panelSaveLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publihserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addComponent(quantityField)
                        .addComponent(auhtorField, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addComponent(publihserField1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSaveLayout.setVerticalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(saveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auhtorField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publihserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publihserField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        panelData.add(panelSave, "panelSave");

        panelDelete.setBackground(new java.awt.Color(255, 255, 255));
        panelDelete.setForeground(new java.awt.Color(0, 0, 0));

        deleteTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deleteTitle.setForeground(new java.awt.Color(0, 0, 0));
        deleteTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteTitle.setText("Delete Book");
        deleteTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        deleteNameInputLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteNameInputLabel.setText("Book Name");

        deleteBookINameInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        deleteFindBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteFindBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteFindBtn.setText("Search");
        deleteFindBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteFindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFindBtnActionPerformed(evt);
            }
        });

        deleteInfoSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteInfoSearch.setText("Find the book you want to delete");

        deleteAuthorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteAuthorLabel.setText("Auhtor");

        deleteNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteNameLabel.setText("Book Name");

        deletePublisherLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletePublisherLabel.setText("Publisher");

        deleteQuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteQuantityLabel.setText("Quantity");

        deleteNameBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        deleteAuthorBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        deletePubllisherBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        deleteQuantityBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        deleteBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBookBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteBookBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBookBtn.setText("DELETE");
        deleteBookBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        deleteBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookBtnActionPerformed(evt);
            }
        });

        deleteInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(deleteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(deletePublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletePubllisherBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(deleteAuthorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAuthorBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteNameInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeleteLayout.createSequentialGroup()
                                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteBookINameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(deleteFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteNameBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(deleteQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDeleteLayout.createSequentialGroup()
                                .addComponent(deleteBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(deleteQuantityBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(deleteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteNameInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBookINameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteNameBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteAuthorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAuthorBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletePublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deletePubllisherBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteQuantityBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(deleteInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        panelData.add(panelDelete, "panelDelete");

        panelFind.setBackground(new java.awt.Color(255, 255, 255));
        panelFind.setName("panelFind"); // NOI18N

        findTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        findTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        findTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        findTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findTitleLabel.setText("Search Book");

        findBookNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findBookNameLabel.setText("Book Name");

        findBookNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findBookNameBtn.setBackground(new java.awt.Color(255, 255, 255));
        findBookNameBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findBookNameBtn.setForeground(new java.awt.Color(0, 0, 0));
        findBookNameBtn.setText("Search");
        findBookNameBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        findBookNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBookNameBtnActionPerformed(evt);
            }
        });

        findInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findInfoLabel.setText("Search book data");

        findLabelBookName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findLabelBookName.setText("Book Name");

        findLabelBookAuhtor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findLabelBookAuhtor.setText("Auhtor");

        findLabelBookPublisher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findLabelBookPublisher.setText("Publisher");

        findLabelBookQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findLabelBookQuantity.setText("Quantity");

        findBookUpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        findBookUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findBookUpdateBtn.setForeground(new java.awt.Color(0, 0, 0));
        findBookUpdateBtn.setText("UPDATE");
        findBookUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBookUpdateBtnActionPerformed(evt);
            }
        });

        findBookDeleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        findBookDeleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findBookDeleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        findBookDeleteBtn.setText("DELETE");
        findBookDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBookDeleteBtnActionPerformed(evt);
            }
        });

        findBookName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findBookPublisher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findBookQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findInfoResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelFindLayout = new javax.swing.GroupLayout(panelFind);
        panelFind.setLayout(panelFindLayout);
        panelFindLayout.setHorizontalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(findTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(panelFindLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFindLayout.createSequentialGroup()
                        .addComponent(findLabelBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFindLayout.createSequentialGroup()
                        .addComponent(findLabelBookAuhtor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFindLayout.createSequentialGroup()
                        .addComponent(findLabelBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFindLayout.createSequentialGroup()
                        .addComponent(findBookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFindLayout.createSequentialGroup()
                                .addComponent(findBookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(findBookNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelFindLayout.createSequentialGroup()
                        .addComponent(findLabelBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFindLayout.createSequentialGroup()
                                .addComponent(findBookDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235)
                                .addComponent(findBookUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(findBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findInfoResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFindLayout.setVerticalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(findTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findLabelBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findLabelBookAuhtor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findLabelBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findLabelBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBookUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(findInfoResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelData.add(panelFind, "panelFind");

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setName("panelUpdate"); // NOI18N

        updateTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        updateTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        updateTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        updateTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateTitleLabel.setText("Update Book");

        updateBookInputLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateBookInputLabel.setText("Book Name");

        updateBookInputField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        updateSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateSearchBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateSearchBtn.setForeground(new java.awt.Color(0, 0, 0));
        updateSearchBtn.setText("Search");
        updateSearchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        updateSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSearchBtnActionPerformed(evt);
            }
        });

        updateInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateInfoLabel.setText("Find the book you want to update");

        updateNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateNameLabel.setText("Book Name");

        updateAuhtorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateAuhtorLabel.setText("Auhtor");

        updatePublihserLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePublihserLabel.setText("Publisher");

        updateQuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateQuantityLabel.setText("Quantity");

        updateAuhtorField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        updatePublisherField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        updateQuantityField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateQuantityField.setText("0");

        updateBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBookBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBookBtn.setForeground(new java.awt.Color(0, 0, 0));
        updateBookBtn.setText("Update");
        updateBookBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        updateBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookBtnActionPerformed(evt);
            }
        });

        updateInfoResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        updateNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(updateTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(updatePublihserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatePublisherField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(updateAuhtorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateAuhtorField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(updateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(updateBookInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(updateBookInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(updateSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(updateQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(updateBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateInfoResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(updateTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBookInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBookInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateAuhtorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateAuhtorField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePublihserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePublisherField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateInfoResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        panelData.add(panelUpdate, "panelUpdate");

        panelAccount.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Email");

        emailAccountField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Id");

        accountIdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Name");

        nameAccountField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Username");

        usernameAccountField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDeleteUser.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteUser.setText("DELETE ACCOUNT");
        btnDeleteUser.setBorder(null);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        infoDeleteAcct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAccountLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAccountLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(infoDeleteAcct, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(emailAccountField, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))))
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccountLayout.createSequentialGroup()
                        .addComponent(usernameAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoDeleteAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        panelData.add(panelAccount, "panelAccount");

        jSplitPane2.setRightComponent(panelData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        cardLayout.show(panelData, "panelSave");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        cardLayout.show(panelData, "panelDelete");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        cardLayout.show(panelData, "panelFind");
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        cardLayout.show(panelData, "panelUpdate");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void auhtorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auhtorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auhtorFieldActionPerformed

    private void publihserField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publihserField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publihserField1ActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        log.info("Request to server : save book");

        String bookName = nameField.getText();
        String author = auhtorField.getText();
        String publisher = publihserField1.getText();
        int quantity = Integer.parseInt(quantityField.getText());

        if (bookName.isEmpty() || author.isEmpty() || publisher.isEmpty() || quantity < 0) {
            labelInfo.setForeground(Color.RED);
            labelInfo.setText("PLEASE FILL ALL DATA BOOK");
            log.error("Failed to save the book!!! data can't empty");
        }else{
            Book book = new Book(bookName, author, publisher, quantity);
            var response = bookService.save(book);
            
            switch (response) {
                case SUCCESS -> {
                    labelInfo.setForeground(Color.GREEN);
                    labelInfo.setText("SUCCESSFULLY SAVE THE BOOK");
                    log.info("Response from server: "+ Response.SUCCESS.getDescription() + " - Success save book");
                }
                case ERROR -> {
                    labelInfo.setForeground(Color.RED);
                    labelInfo.setText("Book Name is already in database");
                    
                    log.info("Response from server: "+ Response.ERROR.getDescription() + " - FAILED save book");
                }
                default -> {
                    labelInfo.setForeground(Color.RED);
                    labelInfo.setText("SOMETHING WRONG, please try again!!!");
                    
                    log.info("Response from server: "+ Response.SUCCESS.getDescription() + " - FAILED save book");
                }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       log.info("{} logout", user.getUsername());
       dispose();
       new LoginView();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountIdField.setText(user.getId());
        nameAccountField.setText(user.getName());
        usernameAccountField.setText(user.getUsername());
        emailAccountField.setText(user.getEmail());
        cardLayout.show(panelData, "panelAccount");
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        log.info("Request : delete account");
        var response = userService.delete(user.getUsername());
        switch (response) {
            case SUCCESS -> {
                log.info("Response : {}", Response.SUCCESS);
                infoDeleteAcct.setText("SUCCESS DELETED ACCOUNT, PLEASE LOGIN AGAIN!!!");
            }
            case FAILED -> { 
                log.info("Response : {}", Response.FAILED);
                infoDeleteAcct.setText("FAILED DELETED ACCOUNT, USER IS NOT FOUND");
            }
            case ERROR -> {
                log.info("Response : {}", Response.ERROR);
                infoDeleteAcct.setText("ERROR WHILE DELETE ACCOUNT, PLEASE TRY AGAIN LATER");
            }
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void deleteFindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFindBtnActionPerformed
        String bookName = deleteBookINameInput.getText();
        
        if (!bookName.isBlank()) {
            log.info("Request : Search book = {}", bookName);
            Book book = bookService.read(bookName);
            if (book != null) {
                log.info("Response : Book Found");
                deleteInfoLabel.setText("");
                deleteNameBookLabel.setText(book.getName());
                deleteAuthorBookLabel.setText(book.getAuthor());
                deletePubllisherBookLabel.setText(book.getPublisher());
                deleteQuantityBookLabel.setText(String.valueOf(book.getQuantity()));
            } else {
                log.info("Response : Book is not found");
                deleteNameBookLabel.setText("");
                deleteAuthorBookLabel.setText("");
                deletePubllisherBookLabel.setText("");
                deleteQuantityBookLabel.setText("0");
                deleteInfoLabel.setText("BOOK NOT FOUND");
                deleteInfoLabel.setForeground(Color.RED);
            }
        } else {
            log.info("FIELD IS EMPTY", Response.FAILED.name());
            deleteInfoLabel.setText("Search Field Cannot Be Empty");
            deleteInfoLabel.setForeground(Color.RED);
        }
        
    }//GEN-LAST:event_deleteFindBtnActionPerformed

    private void deleteBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookBtnActionPerformed
        String bookName = deleteNameBookLabel.getText();
        if (!bookName.isBlank()) {
            log.info("Request : delete book = {}", bookName);
            var response = bookService.delete(bookName);
            switch (response) {
                case SUCCESS -> {
                    log.info("Response : {}", Response.SUCCESS.name());
                    deleteInfoLabel.setText("Book deleted successfully");
                    deleteInfoLabel.setForeground(Color.GREEN);
                }
                case FAILED -> {
                    log.info("Response : {} - Book not found", Response.FAILED.name());
                    deleteInfoLabel.setText("Book not found");
                    deleteInfoLabel.setForeground(Color.RED);
                }
                case ERROR -> {
                    log.info("Response : {}", Response.ERROR.name());
                    deleteInfoLabel.setText("Something error. The book failed to delete");
                    deleteInfoLabel.setForeground(Color.RED);
                }
                default -> throw new AssertionError();
            }
        } else {
            log.info("FIELD IS EMPTY", Response.FAILED.name());
            deleteInfoLabel.setText("Book data is Empty");
            deleteInfoLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_deleteBookBtnActionPerformed

    private void findBookNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBookNameBtnActionPerformed
        String bookName = findBookNameField.getText();
        
        if (!bookName.isBlank()) {
            log.info("Request : Search book = {}", bookName);
            Book book = bookService.read(bookName);
            if (book != null) {
                log.info("Response : Book Found");
                findInfoResultLabel.setText("");
                findBookName.setText(book.getName());
                findBookAuthor.setText(book.getAuthor());
                findBookPublisher.setText(book.getPublisher());
                findBookQuantity.setText(String.valueOf(book.getQuantity()));
            } else {
                log.info("Response : Book is not found");
                findBookName.setText("");
                findBookAuthor.setText("");
                findBookPublisher.setText("");
                findBookQuantity.setText("0");
                findInfoResultLabel.setText("BOOK NOT FOUND");
                findInfoResultLabel.setForeground(Color.RED);
            }
        } else {
            log.info("FIELD IS EMPTY", Response.FAILED.name());
            findInfoResultLabel.setText("Search Field Cannot Be Empty");
            findInfoResultLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_findBookNameBtnActionPerformed

    private void findBookDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBookDeleteBtnActionPerformed
        cardLayout.show(panelData, "panelDelete");
    }//GEN-LAST:event_findBookDeleteBtnActionPerformed

    private void findBookUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBookUpdateBtnActionPerformed
        cardLayout.show(panelData, "panelUpdate");
    }//GEN-LAST:event_findBookUpdateBtnActionPerformed

    private void updateSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSearchBtnActionPerformed
        String bookName = updateBookInputField.getText();
        log.info("Request : Search book = {}", bookName);
        
        if (!bookName.isBlank()) {
            Book book = bookService.read(bookName);
            if (book != null) {
                log.info("Response : Book Found");
                updateInfoResultLabel.setText("");
                updateNameField.setText(book.getName());
                updateAuhtorField.setText(book.getAuthor());
                updatePublisherField.setText(book.getPublisher());
                updateQuantityField.setText(String.valueOf(book.getQuantity()));
            } else {
                log.info("Response : Book is not found");
                updateNameField.setText("");
                updateAuhtorField.setText("");
                updatePublisherField.setText("");
                updateQuantityField.setText("0");
                updateInfoResultLabel.setText("BOOK NOT FOUND");
                updateInfoResultLabel.setForeground(Color.RED);
            }
        } else {
            log.info("FIELD IS EMPTY", Response.FAILED.name());
            updateInfoResultLabel.setText("Search Field Cannot Be Empty");
            updateInfoResultLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_updateSearchBtnActionPerformed

    private void updateBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookBtnActionPerformed
        String bookName = updateNameField.getText();
        String author = updateAuhtorField.getText();
        String publisher = updatePublisherField.getText();
        int quantity = Integer.parseInt(updateQuantityField.getText());
        
        if (author.isEmpty() || publisher.isEmpty() || quantity < 0) {
            updateInfoResultLabel.setForeground(Color.RED);
            updateInfoResultLabel.setText("PLEASE FILL ALL DATA BOOK");
            log.error("Failed to save the book!!! data can't empty");
        }else{
            Book book = new Book(bookName, author, publisher, quantity);
            var response = bookService.update(book);
            
            switch (response) {
                case SUCCESS -> {
                    updateInfoResultLabel.setForeground(Color.GREEN);
                    updateInfoResultLabel.setText("SUCCESSFULLY UPDATE THE BOOK");
                    log.info("Response server: "+ Response.SUCCESS.getDescription() + " - Success update book");
                }
                case FAILED -> {
                    updateInfoResultLabel.setForeground(Color.RED);
                    updateInfoResultLabel.setText("BOOK IS NOT FOUND");
                    
                    log.info("Response server: "+ Response.ERROR.getDescription() + " - FAILED to update book");
                }
                case ERROR -> {
                    updateInfoResultLabel.setForeground(Color.RED);
                    updateInfoResultLabel.setText("Something Failed, Please Try Again later");
                    
                    log.info("Response server: "+ Response.ERROR.getDescription() + " - FAILED to update book");
                }
            }
        }
    }//GEN-LAST:event_updateBookBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIdField;
    private javax.swing.JTextField auhtorField;
    private java.awt.Label authorLabel1;
    private javax.swing.JButton btnAccount;
    private java.awt.Button btnDelete;
    private javax.swing.JButton btnDeleteUser;
    private java.awt.Button btnFind;
    private javax.swing.JButton btnLogout;
    private java.awt.Button btnSave;
    private javax.swing.JButton btnSubmit;
    private java.awt.Button btnUpdate;
    private javax.swing.JLabel deleteAuthorBookLabel;
    private javax.swing.JLabel deleteAuthorLabel;
    private javax.swing.JButton deleteBookBtn;
    private javax.swing.JTextField deleteBookINameInput;
    private javax.swing.JButton deleteFindBtn;
    private javax.swing.JLabel deleteInfoLabel;
    private javax.swing.JLabel deleteInfoSearch;
    private javax.swing.JLabel deleteNameBookLabel;
    private javax.swing.JLabel deleteNameInputLabel;
    private javax.swing.JLabel deleteNameLabel;
    private javax.swing.JLabel deletePublisherLabel;
    private javax.swing.JLabel deletePubllisherBookLabel;
    private javax.swing.JLabel deleteQuantityBookLabel;
    private javax.swing.JLabel deleteQuantityLabel;
    private javax.swing.JLabel deleteTitle;
    private javax.swing.JLabel emailAccountField;
    private javax.swing.JLabel findBookAuthor;
    private javax.swing.JButton findBookDeleteBtn;
    private javax.swing.JLabel findBookName;
    private javax.swing.JButton findBookNameBtn;
    private javax.swing.JTextField findBookNameField;
    private javax.swing.JLabel findBookNameLabel;
    private javax.swing.JLabel findBookPublisher;
    private javax.swing.JLabel findBookQuantity;
    private javax.swing.JButton findBookUpdateBtn;
    private javax.swing.JLabel findInfoLabel;
    private javax.swing.JLabel findInfoResultLabel;
    private javax.swing.JLabel findLabelBookAuhtor;
    private javax.swing.JLabel findLabelBookName;
    private javax.swing.JLabel findLabelBookPublisher;
    private javax.swing.JLabel findLabelBookQuantity;
    private javax.swing.JLabel findTitleLabel;
    private javax.swing.JLabel infoDeleteAcct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel nameAccountField;
    private javax.swing.JTextField nameField;
    private java.awt.Label nameLabel;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelFind;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSave;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTextField publihserField1;
    private java.awt.Label publihserLabel1;
    private javax.swing.JTextField quantityField;
    private java.awt.Label quantityLabel;
    private java.awt.Label saveLabel;
    private javax.swing.JTextField updateAuhtorField;
    private javax.swing.JLabel updateAuhtorLabel;
    private javax.swing.JButton updateBookBtn;
    private javax.swing.JTextField updateBookInputField;
    private javax.swing.JLabel updateBookInputLabel;
    private javax.swing.JLabel updateInfoLabel;
    private javax.swing.JLabel updateInfoResultLabel;
    private javax.swing.JLabel updateNameField;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JLabel updatePublihserLabel;
    private javax.swing.JTextField updatePublisherField;
    private javax.swing.JTextField updateQuantityField;
    private javax.swing.JLabel updateQuantityLabel;
    private javax.swing.JButton updateSearchBtn;
    private javax.swing.JLabel updateTitleLabel;
    private javax.swing.JLabel usernameAccountField;
    // End of variables declaration//GEN-END:variables
}
