/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package book.store.main;

import book.store.gui.Login;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new Login();
    }
}
