/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package book.store.main;

import book.store.view.LoginView;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new LoginView();
    }
}
